[providers]
java = "17"

[variables]
SPRING_PROFILES_ACTIVE = "prod"
JAVA_OPTS = "-Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.awt.headless=true"

[phases.build]
cmds = [
    "chmod +x mvnw",
    "./mvnw clean package -DskipTests -B"
]

[start]
cmd = "java -Dserver.port=$PORT $JAVA_OPTS -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -jar target/*.jar"