services:
  - type: web
    name: kotlin-ai-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: OPEN_AI_KEY
        sync: false 
      - key: QDRANT_HOST_URL
        sync: false 
      - key: QDRANT_API_KEY
        sync: false
      - key: REDIS_HOST_URL
        sync: false
      - key: REDIS_PORT
        value: 6380
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL_ENABLED
        value: true
      # CRITICAL: Disable embedding generation in production
      - key: EMBEDDING_GENERATION_ENABLED
        value: false
      # Memory optimization
      - key: JAVA_OPTS
        value: "-Xmx350m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"