services:
  - type: web
    name: kotlin-ai-chatbot
    runtime: docker
    plan: free
    
    dockerfilePath: ./Dockerfile
    
    healthCheckPath: /api/health
    
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      - key: OPENAI_API_KEY
        sync: false
      
      - key: QDRANT_HOST
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "10457"
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "true"
      
      - key: JAVA_OPTS
        value: "-Xmx350m -Xms128m"